version: '3.8'

services: # MongoDB
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
      MONGO_INITDB_DATABASE: mymongodb

  mssql: # Microsoft SQL
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: examplepassword
      ACCEPT_EULA: Y
      MSSQL_PID: Express
      MSSQL_DATABASE: mymssql

  redis: # REDIS
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  node_app: # Nuxt App
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - mssql
      - redis

volumes:
  mongodb_data:
